import os
import json
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import ValidationError, BaseModel
from typing import List
import logging

from models import SeedInput, KnowledgeGraphExtraction
from database import db
from graphrag import extract_entities_and_relationships
import subprocess

class RunRequest(BaseModel):
    target_url: str
    threat_actor: str = "Cl0p"
    defensive_posture: str = ""

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Threat Graph API",
    description="FastAPI service to ingest threat intelligence and construct a Neo4j Knowledge Graph.",
    version="1.0.0"
)

# Add CORS middleware for the Vue Dashboard
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
def startup_event():
    db.connect()

@app.on_event("shutdown")
def shutdown_event():
    db.close()

@app.post("/api/extract", response_model=KnowledgeGraphExtraction)
def extract_and_store(seed_input: SeedInput):
    """
    Accepts seed input (CVE text, organization tech stack, and threat actor name).
    Uses GraphRAG to extract entities and insert them into a Neo4j database.
    """
    try:
        # Step 1: Extract entities and relationships using LLM
        graph_data = extract_entities_and_relationships(seed_input)
        
        # Step 2: Ingest into Neo4j
        db.merge_graph(graph_data.entities, graph_data.relationships)
        
        return graph_data
    except ValidationError as e:
        logger.error(f"Validation error: {e}")
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        logger.error(f"Error processing request: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/logs")
async def get_simulation_logs():
    """Retrieve the chronological simulation event logs."""
    log_file = "simulation_events.log"
    if not os.path.exists(log_file):
        return []
    
    logs = []
    try:
        with open(log_file, "r") as f:
            for line in f:
                logs.append(json.loads(line.strip()))
        return logs
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error reading logs: {str(e)}")

@app.get("/api/report")
async def get_simulation_report():
    """Retrieve the structured Pydantic JSON report generated by the ReportAgent."""
    report_file = "report.json"
    if not os.path.exists(report_file):
        raise HTTPException(status_code=404, detail="JSON report not found. Run reporter.py first.")
    
    try:
        with open(report_file, "r") as f:
            return json.load(f)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/download")
async def download_pdf_report():
    """Serve the final PDF report for download."""
    pdf_file = "report.pdf"
    if not os.path.exists(pdf_file):
        raise HTTPException(status_code=404, detail="PDF report not found. Run reporter.py first.")
    
    return FileResponse(
        path=pdf_file,
        filename="Threat_Simulation_Report.pdf",
        media_type="application/pdf"
    )

@app.get("/api/health")
def health_check():
    neo4j_status = "connected" if db.driver else "disconnected"
    return {"status": "healthy", "neo4j": neo4j_status}

current_pipeline_stage = "idle"

@app.get("/api/status")
def get_pipeline_status():
    global current_pipeline_stage
    return {"stage": current_pipeline_stage}

@app.post("/api/run")
async def run_simulation(request: RunRequest):
    import subprocess, json, sys
    python = sys.executable
    
    if request.defensive_posture:
        with open("defensive_context.txt", "w") as f:
            f.write(request.defensive_posture)
    
    subprocess.run([python, "ingest.py", request.target_url], check=True)
    subprocess.run([python, "simulation.py", request.threat_actor], check=True)
    subprocess.run([python, "reporter.py"], check=True)
    
    # Return the report
    with open("report.json") as f:
        return json.load(f)
