<template>
  <div class="glass-panel p-6 flex flex-col justify-center items-center text-center">
    <DownloadCloud class="w-12 h-12 text-cyber-accent mb-4 animate-pulse opacity-80" />
    <h3 class="text-2xl font-bold tracking-widest text-cyber-text mb-2">INTELLIGENCE REPORT</h3>
    <p class="text-sm text-cyber-muted mb-6 max-w-sm">
      Download the comprehensive PDF executive summary generated by the Threat Responder AI pipeline.
    </p>
    
    <button @click="downloadPdf" 
            :disabled="!isReady"
            class="group relative px-6 py-3 font-mono font-bold tracking-widest uppercase overflow-hidden rounded bg-cyber-accent/10 border border-cyber-accent text-cyber-accent transition-all hover:bg-cyber-accent hover:text-black hover:shadow-[0_0_20px_rgba(0,240,255,0.6)] disabled:opacity-50 disabled:cursor-not-allowed disabled:border-cyber-muted disabled:text-cyber-muted disabled:hover:bg-transparent">
       <span class="relative z-10 flex items-center gap-2">
         <FileText class="w-4 h-4" />
         {{ isReady ? 'DOWNLOAD PDF' : 'ARCHIVE UNAVAILABLE' }}
       </span>
    </button>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { DownloadCloud, FileText } from 'lucide-vue-next';
import axios from 'axios';

const isReady = ref(false);

const checkStatus = async () => {
    try {
      await axios.head('http://localhost:8000/api/report');
      isReady.value = true;
    } catch {
      isReady.value = false;
    }
}

const downloadPdf = () => {
  window.open('http://localhost:8000/api/download', '_blank');
}

onMounted(() => {
  checkStatus();
  setInterval(checkStatus, 5000); // Poll report availability
})
</script>
